### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sashaafm** [peburrows/goth#1]
Hello is this project dead? I'm trying to get a token for Cloud Storage but it doesn't seem to work:

```
{:ok, token} = Token.for_scope("https://www.googleapis.com/storage/v1/b")
** (MatchError) no match of right hand side value: :error
    (goth) lib/goth/client.ex:35: Goth.Client.jwt/2
    (goth) lib/goth/client.ex:10: Goth.Client.get_access_token/1
    (goth) lib/goth/token.ex:66: Goth.Token.retrieve_and_store!/1
```

**Comment by peburrows** [comment]
No, the project isn't dead at all. In fact, it's just a baby :)

If you don't mind providing more information about how to reproduce the issue, I'd be happy to track it down.

**Comment by sashaafm** [comment]
Hello @peburrows I just solved my problem this morning. As you can see in the code I'm using the wrong URL for scope. I inserted the correct one for Cloud Storage and it works now. But thanks!

What other features are you thinking of implementing?

**Comment by peburrows** [comment]
@sashaafm currently, Goth's only responsibility is to retrieve and manage access tokens. I've written [Kane](https://github.com/peburrows/kane) for Pub/Sub, and I'm currently also working on a library for Datastore.

My plan is to build libraries for specific Google APIs, all of which will use Goth for token management.

**Comment by sashaafm** [comment]
@peburrows I'm also building a client/library to most of Google Cloud Platform API's. Right now I'm doing Google Cloud Platform, and I'm using your Goth app for authentication :+1: I started it just a couple of days ago.

[www.github.com/sashaafm/gcloudex](url)

Are you interested in collaborating to build the library together?

**Comment by peburrows** [comment]
@sashaafm I'd totally be open to collaboration. I'll take a look at your code and will also update this issue when I have something worth looking at for my Datastore lib.

Thanks for reaching out!

**Comment by sashaafm** [comment]
No problem @peburrows :) Look forward to hearing from you. I'm aiming at doing Storage and Compute Engine until May.

P.S. I meant I'm working on the client for Google Cloud Storage right now.
