### ISSUE TITLE
Is it possible generate oauth token without using service account?

### ISSUE THREAD

**Issue by gr8Adakron** [peburrows/goth#109]
Hey, For working with development env `goth` works smooth as butter, but while deploying the app in kubernetes I already  have `Kubernetes Service Account` binded to `Google Service Account` however is there a way to directly pass the Kubernetes Service Account identity to goth instead of JSON file? 

As in production from security perspective using JSON file is not a good practise.

**Comment by wojtekmach** [comment]
I'm going to close this as it's not on the roadmap but a PR with another `:source` value specific for Kubernetes would be appreciated!
