### ISSUE TITLE
example does not work.

### ISSUE THREAD

**Issue by devalexandre** [peburrows/goth#117]
I tested the example shown in the readme, but even so it keeps giving error, is there any more complete documentation?

![image](https://user-images.githubusercontent.com/4489558/150724704-3f0ffd2d-fb63-4777-b92a-11313f911b2c.png)

mix.exs

![image](https://user-images.githubusercontent.com/4489558/150724757-c5240f9f-8b43-40e2-b5dc-fa19cda3eb53.png)

Error:
![image](https://user-images.githubusercontent.com/4489558/150724828-bb710d19-5cf0-4511-afa7-6589478de3b9.png)

**Comment by wojtekmach** [comment]
Note the crash happens in your Logger.info call. We cannot print maps as is. Change `#{credentials}` to `#{inspect(credentials)}` and same for `source` line below. Does that help?

**Comment by devalexandre** [comment]
> Note the crash happens in your Logger.info call. We cannot print maps as is. Change `#{credentials}` to `#{inspect(credentials)}` and same for `source` line below. Does that help?

I remove a Logger.
![image](https://user-images.githubusercontent.com/4489558/150779304-79e9d15a-392c-4896-87e4-d30445c537a2.png)

![image](https://user-images.githubusercontent.com/4489558/150779357-8d519fe0-5caa-444a-8c16-3b79389a40f7.png)

**Comment by wojtekmach** [comment]
I could see in the earlier stack trace that you had `"type" => "authorized_user"` in your credentials. The credentials must be for the service account. You can create them for example like this:

```
$ gcloud iam service-accounts keys create --key-file-type=json --iam-account=... credentials.json
```
