### ISSUE TITLE
Document refresh token

### ISSUE THREAD

**Issue by mrdotb** [peburrows/goth#118]
Hello,

I struggled a bit to find the correct token to upload video on youtube it does not work with service account. I realize later that goth 1.3 support `refresh_token` when I read the code.
I wrote [upload on youtube with elixir](https://mrdotb.com/posts/upload-on-youtube-with-elixir/)
The part to get the refresh token could be useful for goth users.

**Comment by wojtekmach** [comment]
Thank you for creating the walkthrough! I'm not sure how to best integrate it into our docs. Perhaps a section at the bottom of the README with community resources? I'm gonna close the issue in the meantime, but please feel free to send a PR.
