### ISSUE TITLE
unknown registry Goth.Registry

### ISSUE THREAD

**Issue by alexanderttalvarez** [peburrows/goth#144]
Hello!

After upgrading to Goth 1.3, and following the instructions [here](https://github.com/peburrows/goth/blob/master/UPGRADE_GUIDE.md), we are receiving an error `unknown registry Goth.Registry`. Looks like the registry is never started. Is there anything missing in the docs?

![Captura de Pantalla 2022-08-06 a las 8 59 30](https://user-images.githubusercontent.com/22129087/183238276-68ff9c5f-eab6-41a3-bcac-3403f22fa6e6.png)

Thank you!

**Comment by wojtekmach** [comment]
This is very odd, it seems the goth app wasn't properly started. Do you have by any chance either:

`{:goth, ..., runtime: false}`

or

```
def application do
  [
    applications: [...] # the list does _not_ contain goth
  ]
end
```

?

**Comment by alexanderttalvarez** [comment]
Oh I see! We have the `runtime: false` one. We are only using Goth inside a Script, we don't want to use it during runtime. How can we keep using the `runtime: false` flag?

Thank you!

**Comment by wojtekmach** [comment]
Do:    
        
```elixir
{:ok, _} = Application.ensure_all_started(:goth)
```

at the beginning of the script!
