### ISSUE TITLE
Need for documentation about configuration

### ISSUE THREAD

**Issue by shellking4** [peburrows/goth#150]
First thank you for this work. 
I'm trying since two hours to get the access_token using this package but it's such difficult to figure out how to configure things properly
I already have my credentials.json

`{
    "web": {
        "client_id": "******",
        "project_id": "******",
        "auth_uri": "*****",
        "token_uri": "*****",
        "auth_provider_x509_cert_url": "*******",
        "client_secret": "***********"
    }
}`

Now my question how to configure the things in the application, I'm using phoenix. 
I'm also availble to help write more documentation for the package. Thank you

**Comment by wojtekmach** [comment]
Goth supports fetching token using service account, refresh token, or internal metadata service but it seems you have credentials for web-based flow which is not supported.

**Comment by wojtekmach** [comment]
I closed the issue as supporting that flow is not on the roadmap but of course feel free to keep discussing it. I'd try authenticating using service account as that is the more common and once you've Goth working there, try different things.
