### ISSUE TITLE
Error when call for_scope

### ISSUE THREAD

**Issue by kungfu321** [peburrows/goth#25]
I'm using {:ok, goth} = Goth.Token.for_scope("https://www.googleapis.com/auth/devstorage.full_control")
But i seen a bug. Please help me

** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :crypto.mpint/1 is undefined or private
        (crypto) :crypto.mpint(19687873431742193920055970243130294467124206658682087298983794038798216955530975915146333586732314900700035611611045789143545904247799428447896803420118324471667046274052296120024954651561469080093219328190691149886440049200669636272584661976356321702914680136369124759272732574776698998044554776915282967732669956832401458331945711479325049514685797410840542208523089896590986235120222095570675226125560522026179882816977851505433864383972624362893774956738669017687990725035030542706539434148824251987312659383648295704127681204473207295376320651645980971185202320992998884262991006767805018245431366563316696488933)

**Comment by dazuma** [comment]
@kungfu321 Make sure you are using the latest releases of goth (0.6.0) and json_web_token (0.2.10). This issue, I believe, appears in older versions of json_web_token when running on Erlang 20. (See https://github.com/garyf/json_web_token_ex/pull/22)
