### ISSUE TITLE
Change format of environment variable?

### ISSUE THREAD

**Issue by brandonparsons** [peburrows/goth#27]
Hi there,

Is there any way to make it possible to accept a Base 64 encoded version of the JSON auth credentials? The huge JSON string is a bit unwieldy.

**Comment by peburrows** [comment]
I think this would definitely be a handy addition, but I need to think about how we might go about doing this.

**Comment by peburrows** [comment]
Now that #32 is merged, you should be able to do this yourself as part of an `init` callback. As such, I'm going to close this issue.
