### ISSUE TITLE
sub Support

### ISSUE THREAD

**Issue by chengyin** [peburrows/goth#29]
I noticed that there are two PRs (#7, #12) on this. Before I try to work on the 3rd one, is this something this lib wants to support?

**Comment by chengyin** [comment]
Just noticed that the new version does have this! Sorry about the spam.

**Comment by chengyin** [comment]
The new `actor_email` config only applies to one user. What if I need to dynamically change who to personate in each call?

**Comment by peburrows** [comment]
Currently, there's no way to do this dynamically, unfortunately. The `actor_email` config was added to fill the gap in functionality, but longer term I'd like to provide a more flexible way of doing things.

I might have some time to work on this feature next week, but as always, PRs are more than welcomed!

**Comment by chengyin** [comment]
I made the changes since I need the feature. PTAL at the PR. Thanks!
