### ISSUE TITLE
Update httpoison version?

### ISSUE THREAD

**Issue by dsignr** [peburrows/goth#38]
Just a suggestion, currently goth uses 0.11, but the latest httpoison version is 1.0. I followed here all the way from https://github.com/sashaafm/gcloudex :)

**Comment by peburrows** [comment]
Yep, should be no harm updating to the latest httpoison. I'll add this to my todo list.

**Comment by dsignr** [comment]
Thanks for the fast response. (A Small correction, I came from [this issue](https://github.com/sashaafm/gcloudex/issues/15) here.)
