### ISSUE TITLE
Joken in v1.0.0 is not working in cloud

### ISSUE THREAD

**Issue by jdrakes** [peburrows/goth#51]
I am trying to use GCP system credentials in Google Cloud and am receiving an error ** (UndefinedFunctionError) function Joken.Signer.create/2 is undefined (module Joken.Signer is not available)

**Comment by amit115532** [comment]
Same here

**Comment by jdrakes** [comment]
@peburrows I got it to work but I had to declare joken in my personal apps mix.exs file instead of it being pulled in when goth was compiled. It does not look like goth is requesting it be compiled into the library. 

@amit using the fix above should work for now.

**Comment by peburrows** [comment]
@jdrakes & @amit115532 — can you try `v1.0.1-beta` I just pushed to Hex? It should address the issue of Joken not being included in releases.

**Comment by amit115532** [comment]
Works using `1.0.1-beta` :)
Thanks! @peburrows
