### ISSUE TITLE
just an error

### ISSUE THREAD

**Issue by vans163** [peburrows/goth#53]
```
{:ok, token} = Goth.Token.for_scope({
...(1)>     "43143433-compute@developer.gserviceaccount.com",
...(1)>     "https://www.googleapis.com/auth/cloud-platform.read-only"})
** (MatchError) no match of right hand side value: :error
    lib/goth/client.ex:44: Goth.Client.get_access_token/2 
    lib/goth/token.ex:150: Goth.Token.retrieve_and_store!/2
```

Im using the JSON file from GCP.

**Comment by lccezinha** [comment]
@vans163 do you mean the option 2 from https://github.com/peburrows/goth#installation?

Could you please post here the config line?

**Comment by vans163** [comment]
I think something was wrong on my end, but I got it working just error was cryptic.

**Comment by bfolkens** [comment]
I'm seeing the same issue with using:

```
config :goth,
  disabled: true
```

**Comment by helenmedrano** [comment]
@vans163 I'm getting this same error. Any chance you remember the fix?

**Comment by wojtekmach** [comment]
If you have more information how to reproduce the error, please let us know.
