### ISSUE TITLE
target_audience claim

### ISSUE THREAD

**Issue by aizotov** [peburrows/goth#58]
Are there any plans to support the `target_audience` claim as described [in the IAP docs](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_service_account) ?

**Comment by wojtekmach** [comment]
There are no plans, if you'd like to work on it however, please make sure you check out https://github.com/peburrows/goth/issues/82 first.

**Comment by paveltyk** [comment]
If someone is looking for how to get a token for Google cloud function invocation, please read more here: https://github.com/peburrows/goth/issues/101
