### ISSUE TITLE
403 Forbidden whenever I try to make a token

### ISSUE THREAD

**Issue by vans163** [peburrows/goth#64]
I transferred the GCP JSON credentials to another system.

```
{:ok, token} = Goth.Token.for_scope("https://www.googleapis.com/auth/cloud-platform")
```

**Comment by peburrows** [comment]
I'm gonna need more information than that;  a `403` could mean a number of different things: https://cloud.google.com/storage/docs/json_api/v1/status-codes#403_Forbidden

**Comment by peburrows** [comment]
Do your credentials work on the system you transferred them from?

**Comment by vans163** [comment]
Yes. creds work fine on that system, i just transferred the project over and did a icloud sdk installation jst incase.

**Comment by vans163** [comment]
Holy shit i never use config files. its had to be called config.exs not config.ex!
