### ISSUE TITLE
Tag v1.2.0

### ISSUE THREAD

**Issue by sgerrand** [peburrows/goth#73]
I noticed that although version 1.2.0 has been released, it hasn't been tagged yet. While GitHub provides a nice visual diff for the [changes which have been merged since v1.1.0](https://github.com/peburrows/goth/compare/v1.1.0...master), this will change as soon as new commits get added.

Would you please tag the commit which was built and pushed to Hex.

**Comment by peburrows** [comment]
Done: https://github.com/peburrows/goth/releases/tag/v1.2.0
