### ISSUE TITLE
Add default source with ADC support

### ISSUE THREAD

**Issue by bbhoss** [peburrows/goth#94]
As mentioned in #77, Goth should support ADC. Additionally Goth should Just Work™️ out of the box without needing to provide an explicit source in the case that default credentials exist. I propose we mirror the google-auth Python library that I suspect most GCP users have experience with. They have the order of defaults to use documented [here](https://github.com/googleapis/google-auth-library-python/blob/333cb765b52028329ec3ca04edf32c5764b1db68/google/auth/_default.py#L346). I propose we mirror this order where Goth supports the auth methods (it's unclear the GAE method is supported).

**Comment by wojtekmach** [comment]
We don't plan to tackle this so I'm going to close this but a PR will be very welcome, thanks!
