### ISSUE TITLE
Suggestion for scope parameter

### ISSUE THREAD

**Issue by sam701** [peburrows/goth#97]
The Goth's `source` parameters has a field `scope`. That is a string but actually it can contain multiple scopes separated by a single space. The code below works:
```elixir
    source = {
      :service_account, credentials,
      scope: "https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.compose",
      sub: "user1@abc.org"
    }
    children = [{Goth, name: :my_goth, source: source}]
    {:ok, _} = Supervisor.start_link(children, strategy: :one_for_one)
```

It would be nice if the `scope` becomes `scopes` and expects a list of strings. Because
* not everybody is familiar with the OAuth2 spec,
* so we could avoid annoying typos in the string, e.g. double spaces, tabs, etc.

**Comment by wojtekmach** [comment]
Sounds good. A PR that changes the `:scope` option to `:scopes` for the `:service_account` source would be appreciated. I think we should still keep it as `:scope` (string) on the `Goth.Token` for backwards compatibility though.
